name: Storefront 1000128740
on: [push]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy to Oxygen
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          check-latest: true

      - name: Install dependencies
        run: npm ci

      - name: Build for Oxygen
        run: npm run build

      - name: Push to Oxygen
        env:
          # Use the shpat_ token from your GitHub Secrets
          SHOPIFY_HYDROGEN_DEPLOYMENT_TOKEN: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_1000128740 }}
        run: |
          # We use the legacy CLI 'push' command which is built for v1
          npx @shopify/cli-hydrogen@2.x push --target worker
